// FORM ACTIONS
export const CHANGE_FORM_STEP: string = 'CHANGE_FORM_STEP';

// USER
export const USER_PASSED_1ST_STEP: string = 'USER_PASSED_1ST_STEP';
export const USER_PASSED_2ND_STEP: string = 'USER_PASSED_2ND_STEP';
export const ASSIGN_DISH_NAME: string = 'ASSIGN_DISH_NAME';
export const ASSIGN_PREPARATION_TIME: string = 'ASSIGN_PREPARATION_TIME';
export const ASSIGN_DISH_TYPE: string = 'ASSIGN_DISH_TYPE';
